---
# included file

- name: Jenkins RPM Key
  rpm_key:
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    state: present
  become: yes

- name: Jenkins YUM Repository
  yum_repository:
    name: jenkinsrepo
    description: Jenkins YUM Repository
    baseurl: http://pkg.jenkins.io/redhat
    gpgcheck: yes
    state: present
  become: yes

- name: Jenkins Installation
  yum:
    name: "{{ jenkins2_version }}"
    disable_gpg_check: "{{ jenkins2_disable_gpg_check }}"
    state: present
  become: yes
