---
# included file

- name: Jenkins CLI
  get_url:
    url: "http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }}/jnlpJars/jenkins-cli.jar"
    dest: /tmp/jenkins-cli.jar
    owner: root
    group: root
    mode: 0444

- name: Groovy Scripts
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: 0444
  with_items:
    - security_realm_name.groovy
    # - proxy_configuration.groovy

- name: Security Realm Checking
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }} groovy /tmp/security_realm_name.groovy"
  register: jenkins2_security_realm_name

- name: CLI Login
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }} login --username {{ jenkins2_cli_username }}  --password {{ jenkins2_cli_password }}"
  when: jenkins2_security_realm_name.stdout != "hudson.security.SecurityRealm$None"

- name: Plugins Installation
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }} install-plugin {{ item }}"
  with_items:
    - "{{ jenkins2_suggested_plugins }}"
    - "{{ jenkins2_plugins }}"
  notify:
    - Restart Jenkins

- name: CLI Logout
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }} logout"
  when: jenkins2_security_realm_name.stdout != "hudson.security.SecurityRealm$None"
